///MDT

OOL
**
 * PLUGIN.JS
 *
 * RELEASED UNDER LGPL LICENSE.
 * COPYRIGHT (C) 1999-2015 EPHOX CORP. ALL RIGHTS RESERVED
 *
 * LICENSE: HTTP://WWW.TINYMCE.COM/LICENSE
 * CONTRIBUTING: HTTP://WWW.TINYMCE.COM/CONTRIBUTING
 */

/*GLOBAL TINYMCE:TRUE */

TINYMCE.PLUGINMANAGER.ADD('INSERTDATETIME', FUNCTION(EDITOR) {
	VAR DAYSSHORT = "SUN MON TUE WED THU FRI SAT SUN".SPLIT(' ');
	VAR DAYSLONG = "SUNDAY MONDAY TUESDAY WEDNESDAY THURSDAY FRIDAY SATURDAY SUNDAY".SPLIT(' ');
	VAR MONTHSSHORT = "JAN FEB MAR APR MAY JUN JUL AUG SEP OCT NOV DEC".SPLIT(' ');
	VAR MONTHSLONG = "JANUARY FEBRUARY MARCH APRIL MAY JUNE JULY AUGUST SEPTEMBER OCTOBER NOVEMBER DECEMBER".SPLIT(' ');
	VAR MENUITEMS = [], LASTFORMAT, DEFAULTBUTTONTIMEFORMAT;

	FUNCTION GETDATETIME(FMT, DATE) {
		FUNCTION ADDZEROS(VALUE, LEN) {
			VALUE = "" + VALUE;

			IF (VALUE.LENGTH < LEN) {
				FOR (VAR I = 0; I < (LEN - VALUE.LENGTH); I++) {
					VALUE = "0" + VALUE;
				}
			}

			RETURN VALUE;
		}

		DATE = DATE || NEW DATE();

		FMT = FMT.REPLACE("%D", "%M/%D/%Y");
		FMT = FMT.REPLACE("%R", "%I:%M:%S %P");
		FMT = FMT.REPLACE("%Y", "" + DATE.GETFULLYEAR());
		FMT = FMT.REPLACE("%Y", "" + DATE.GETYEAR());
		FMT = FMT.REPLACE("%M", ADDZEROS(DATE.GETMONTH() + 1, 2));
		FMT = FMT.REPLACE("%D", ADDZEROS(DATE.GETDATE(), 2));
		FMT = FMT.REPLACE("%H", "" + ADDZEROS(DATE.GETHOURS(), 2));
		FMT = FMT.REPLACE("%M", "" + ADDZEROS(DATE.GETMINUTES(), 2));
		FMT = FMT.REPLACE("%S", "" + ADDZEROS(DATE.GETSECONDS(), 2));
		FMT = FMT.REPLACE("%I", "" + ((DATE.GETHOURS() + 11) % 12 + 1));
		FMT = FMT.REPLACE("%P", "" + (DATE.GETHOURS() < 12 ? "AM" : "PM"));
		FMT = FMT.REPLACE("%B", "" + EDITOR.TRANSLATE(MONTHSLONG[DATE.GETMONTH()]));
		FMT = FMT.REPLACE("%B", "" + EDITOR.TRANSLATE(MONTHSSHORT[DATE.GETMONTH()]));
		FMT = FMT.REPLACE("%A", "" + EDITOR.TRANSLATE(DAYSLONG[DATE.GETDAY()]));
		FMT = FMT.REPLACE("%A", "" + EDITOR.TRANSLATE(DAYSSHORT[DATE.GETDAY()]));
		FMT = FMT.REPLACE("%%", "%");

		RETURN FMT;
	}

	FUNCTION INSERTDATETIME(FORMAT) {
		VAR HTML = GETDATETIME(FORMAT);

		IF (EDITOR.SETTINGS.INSERTDATETIME_ELEMENT) {
			VAR COMPUTERTIME;

			IF (/%[HMSIP]/.TEST(FORMAT)) {
				COMPUTERTIME = GETDATETIME("%Y-%M-%DT%H:%M");
			} ELSE {
				COMPUTERTIME = GETDATETIME("%Y-%M-%D");
			}

			HTML = '<TIME DATETIME="' + COMPUTERTIME + '">' + HTML + '</TIME>';

			VAR TIMEELM = EDITOR.DOM.GETPARENT(EDITOR.SELECTION.GETSTART(), 'TIME');
			IF (TIMEELM) {
				EDITOR.DOM.SETOUTERHTML(TIMEELM, HTML);
				RETURN;
			}
		}

		EDITOR.INSERTCONTENT(HTML);
	}

	EDITOR.ADDCOMMAND('MCEINSERTDATE', FUNCTION() {
		INSERTDATETIME(EDITOR.GETPARAM("INSERTDATETIME_DATEFORMAT", EDITOR.TRANSLATE("%Y-%M-%D")));
	});

	EDITOR.ADDCOMMAND('MCEINSERTTIME', FUNCTION() {
		INSERTDATETIME(EDITOR.GETPARAM("INSERTDATETIME_TIMEFORMAT", EDITOR.TRANSLATE('%H:%M:%S')));
	});

	EDITOR.ADDBUTTON('INSERTDATETIME', {
		TYPE: 'SPLITBUTTON',
		TITLE: 'INSERT DATE/TIME',
		ONCLICK: FUNCTION() {
			INSERTDATETIME(LASTFORMAT || DEFAULTBUTTONTIMEFORMAT);
		},
		MENU: MENUITEMS
	});

	TINYMCE.EACH(EDITOR.SETTINGS.INSERTDATETIME_FORMATS || [
		"%H:%M:%S",
		"%Y-%M-%D",
		"%I:%M:%S %P",
		"%D"
	], FUNCTION(FMT) {
		IF (!DEFAULTBUTTONTIMEFORMAT) {
			DEFAULTBUTTONTIMEFORMAT = FMT;
		}

		MENUITEMS.PUSH({
			TEXT: GETDATETIME(FMT),
			ONCLICK: FUNCTION() {
				LASTFORMAT = FMT;
				INSERTDATETIME(FMT);
			}
		});
	});

	EDITOR.ADDMENUITEM('INSERTDATETIME', {
		ICON: 'DATE',
		TEXT: 'INSERT DATE/TIME',
		MENU: MENUITEMS,
		CONTEXT: 'INSERT'
	});
});
